### ISSUE TITLE
das Feld "sourceOrganization" mit dokumentieren (?)

### ISSUE THREAD

**Issue by zazi** [dini-ag-kim/lrmi-profile#110]
Ich bin mir nicht sicher, ob ich mit diesem Anliegen hier an der richtigen Stelle bin, dennoch versuche es hier erst einmal. In den LRMI-Datensätzen von OERSI kommt auch das Feld "sourceOrganization" vor, z.B. in ["Lernplattform Küsteningenieurwesen"](https://oersi.de/resources/aHR0cDovL2NvYXN0YWwubHdpLnR1LWJzLmRl) bzw. [hier](https://oersi.de/resources/aHR0cDovL2NvYXN0YWwubHdpLnR1LWJzLmRl?format=json) das zugehörige JSON. Das Feld ist (m.E.n.) bis jetzt nicht in der Schema-Dokumentation dieses LRMI-Profils enthalten. Das Feld ["publisher"](https://dini-ag-kim.github.io/lrmi-profile/draft/#publisher) hingegen schon. Das Feld "sourceOrganization" entspricht von seinen aktuellen Inhalten in OERSI (m.E.n.) ungefähr denen, die auch für das Feld ["publisher"](https://dini-ag-kim.github.io/lrmi-profile/draft/#publisher) geeignet sein könnten.
Soll das Feld "sourceOrganization" trotzdem zusätzlich in dieses LRMI-Profil aufgenommen werden? - oder handelt es sich dabei vllt. um eine frühere Version von ["publisher"](https://dini-ag-kim.github.io/lrmi-profile/draft/#publisher)?

**Comment by acka47** [comment]
`sourceOrganization` ist eine OERSI-spezifische Property. In AMB wurde der – bessere – Weg gewählt, über `affiliation` die Zugehörigkeit zu einer Organisation auszudrücken. Für die zugrundeliegende Diskussion siehe #15. (Wenn das für dich erstmal ausreicht, kannst du das Ticket gerne schließen.)
