### ISSUE TITLE
Modularisierung & Ergänzung für den Schulbereich

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/lrmi-profile#23]
Momentan finden einige Parallelarbeiten im Hochschul- und Schulbereich, wo immerhin dieselben Standards, Tools und Prozesse stattfinden. Das LRMI-Profil ist für den Hochschulbereich, wie auch die darin genutzten kontrollierten Vokabulare [HCRT](https://w3id.org/kim/hcrt/scheme) und die [Hochschulfächersystematik](https://w3id.org/kim/hochschulfaechersystematik/scheme).

Für den Schulbereich nutzt @sroertgen auch SKOS/SkoHub (siehe https://vocabs.openeduhub.de/) und möchte auch ein JSON Schema für schema.org/LRMI-basierte Metadaten von Schul-OER als JSON-LD schreiben.

Es ist davon auszugehen, dass einige Teile des Schemas gleichermaßen für beide Bereiche (Schule/Hochschule) verwendet werden können, wohingegen andere für den jeweiligen Bereich angepasst werden müssen. Mit https://github.com/hbz/skohub-editor/pull/55 wird es im SkoHub Editor möglich sein, modularisierte und über URLS aufeinander verweisende JSON Schemas zu verwenden. Im Branch [splitUpSchema](https://github.com/dini-ag-kim/lrmi-profile/tree/splitUpSchema) hatte ich schon einmal einen früheren Stand des Schemas aufgesplittet in modulare Bestandteile.

Wir sollten überlegen, wie und wo wir die generischen Schemabestandteile ablegen, so dass sie von beiden Schemas referenziert und sozusagen importiert werden können.

**Comment by sroertgen** [comment]
Gesprächsnotiz: Ein möglichst generisches Schema wird favorisiert, das auf beide Bereiche grundsätzlich anwendbar ist. In der HTML-Spezifikation kann dann auf jeweils unterschiedliche Wertelisten verwiesen werden.

Wollen wir den Titel der Readme ("LRMI-Profil für Hochschul-OER im deutschsprachigen Raum") dann eventuell auch umbenennen, wenn wir hier ein generelles OER-Schema erarbeiten?

- Vorschlag 1: LRMI-Profil für OER im deutschsprachigen Raum
- Vorschlag 2: LRMI-Profil für Educational Resources im deutschsprachigen Raum

**Comment by acka47** [comment]
Ich habe mal einen PR zur Aktualisierung der Readme gemacht und dir zugewiesen, Steffen: #34

Ich würde dieses Ticket schließen. Der erste Schritt (Modularisierung) wurde abgeschlossen mit #24. Für die Umsetzung der HTML Spec ist das Vorgehen relativ klar und hier auch kein Thema. Für den weiteren Umgang mit dem Schema würde ich lieber konkrete Tickets aufmachen, wenn Fragen aufkommen und wir das weitere Vorgehen diskutiert haben. Ok, @sroertgen ?
