### ISSUE TITLE
Context array mit verschiedenen Datentypen ist inkompatibel mit Elasticsearch

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/lrmi-profile#26]
So etwas kann nicht in ES indexiert werden:

```json
{
  "@context": [ 
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {"@language": "de"}
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": "Course"
}
```
Siehe auch https://www.elastic.co/guide/en/elasticsearch/reference/7.10/array.html:

> When adding a field dynamically, the first value in the array determines the field type. All subsequent values must be of the same data type or it must at least be possible to coerce subsequent values to the same data type.
>
> Arrays with a mixture of data types are not supported

Aus diesem Grund geht das POSTen nach SkoHub nicht mehr vollständig (weil dort ein ES-Index angeschlossen ist), siehe https://github.com/hbz/skohub-pubsub/issues/40#issuecomment-709308665.

Zwar ist das valides JSON-LD und so ähnlich auch in einem Beispiel dokumentiert (https://w3c.github.io/json-ld-syntax/#example-22-combining-external-and-local-contexts), allerdings wäre es schon gut, ES-kompatibles JSON zu produzieren, weil u.a. SkoHub und OERSI auf dem Schema aufbauen. Allerdings sehe ich gerade keine Möglichkeit, das Schema so anzupassen, dass die Daten äquivalent sind und ES-kompatibel.

Zum Beispiel ist das hier **kein valides JSON-LD** (siehe [Playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fw3id.org%2Fkim%2Flrmi-profile%2Fdraft%2Fcontext.jsonld%22%2C%22%40language%22%3A%22de%22%7D%2C%22name%22%3A%22Beispielkurs%22%2C%22id%22%3A%22https%3A%2F%2Fexample.org%2Foer%22%2C%22type%22%3A%22Course%22%7D)):

```json
{
  "@context": {
    "@id": "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    "@language": "de"
  },
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": "Course"
}
```
Die URL des Kontext kann *nicht* mit `@id` angegeben werden.

Die einzige Lösung, die ich sehe: Die Default-Sprache in den externen Kontext eintragen und verschiedene Kontexte anbieten (`context-de.jsonld`, `context-en.jsonld` etc.)

**Comment by fsteeg** [comment]
Since we don't need to search the content of the `@context` field, I think we could disable it (`"enabled": false`) in Elasticsearch, see `session_data.arbitrary_object.some_array` in https://www.elastic.co/guide/en/elasticsearch/reference/7.10/enabled.html

**Comment by acka47** [comment]
Hmm, das wäre eine nette Lösung. Ich bin nicht ganz sicher, ob das überhaupt funktioniert. In https://www.elastic.co/guide/en/elasticsearch/reference/7.10/enabled.html heißt es:

> The enabled setting, which can be applied only to the top-level mapping definition and to object fields,

Wir sollten es am besten einfach mal ausprobieren. @dr0i, kannst du den SkoHub-ES-Index entsprechend konfigurieren?

**Comment by acka47** [comment]
Die Lösung über die ES-Konfiguration funktioniert zum Glück. Dann mach ich das Ticket hier zu.
