### ISSUE TITLE
Type als required?

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/lrmi-profile#30]
Nach dem neuen Entwurf ist type: LearningResource als default gesetzt.  Müsste dann nicht auch type als required vermerkt werden?

https://github.com/dini-ag-kim/lrmi-profile/blob/db896d8a4bb4f7e46745d5a6a2a15b40d34a8493/draft/schemas/schema.json#L13-15

**Comment by acka47** [comment]
Ja, sollten wir machen. Ich hatte hier mal eine Schemaversion, die dann `LearningResource` als notwendig ansieht und weitere Werte erlaubt (wo dann die passenden Werte von https://schema.org/CreativeWork gelistet werden sollten):

https://github.com/dini-ag-kim/lrmi-profile/blob/3ee55c4284fb8956e1d3744e80f0b629e027ae67/draft/schemas/schema.json#L49-L75

Leider funktioniert das zur Zeit nicht mit dem Editor. Du kannst aber gerne einen PR machen, um `type` in den `required` Array aufzunehmen.
