### ISSUE TITLE
Lizenz als required?

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/lrmi-profile#32]
Da das Metadatenprofil für OER bestimmt ist, wäre die notwendige Ausweisung einer Lizenz meiner Meinung nach sinnvoll.

Aus pragmatischer Perspektive sollte das aber ohne vorgeschriebene Werteliste sein, um offene Lizenzen jenseits von Creative Commons und im Kontext von OERSI auch ggf. Ressourcen mit vorbehaltenen Rechten berücksichtigen zu können.

**Comment by acka47** [comment]
Da wir das jetzt eher als allgemeines LRMI-Profil veröffentlichen, sollten die Lizenzangabe nicht verpflichtend sein. Von daher schließe ich das Ticket. (Für OERSI würde uns eine solche Anpassung wahrscheinlich auch erstmal einige Probleme machen.)
