### ISSUE TITLE
Ändere isBasedOn zu Object-Array

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/lrmi-profile#35]
Während des KIM OER-AG Meetings wurde von @lechten vorgeschlagen, dass es ein Feld für Provenienz/provinence geben sollte, um eingebundene und verarbeitete OER zu referenzieren.

Theoretisch passt das bereits berücksichtigte Feld `isBasedOn` dafür.

> A resource from which this work is derived or from which it is a modification or adaption.
(https://schema.org/isBasedOn)

 Um aber Namen, Lizenzen, Urheber etc berücksichtigen zu können, brauchen wir ein Object-Array anstelle des String-Arrays.

**Comment by lechten** [comment]
Aus [CC REL](https://wiki.creativecommons.org/wiki/CC_REL) benutze ich `dc:source` statt `isBasedOn`, zudem `attributionName` und `attributionURL` für die Urheberin.

Weitergehend gibt es die [PROV](https://www.w3.org/TR/prov-overview/)-Sprachfamilie mit `wasDerivedFrom` und `wasAttributedTo` in der [Übersicht](https://www.w3.org/TR/2013/NOTE-prov-primer-20130430/#intuitive-overview-of-prov). 

In der Praxis wüsste ich nicht, welche URI ich bei der Weiternutzung von OER für `wasAttributedTo` benutzen würde. Für mich selbst nutze ich aktuell `https://lechten.gitlab.io/#me`. Empfehlungen wären sinnvoll.

Wenn `isBasedOn` eine [Cool URI](https://www.w3.org/TR/cooluris/) wäre (was ich bei `wasAttributedTo` unterstelle), würde ich bei deren Aufruf die Informationen zu Name, Lizenz usw. erwarten. Gibt es für meine OER aktuell nicht.

**Comment by acka47** [comment]
Hallo Jens, ich war ja beim letzten Treffen nicht dabei aber so wie ich es verstanden habe, geht es dir darum, in deinen OER strukturierte Angaben zu von dir genutzten oder geremixten Ressourcen zu haben, so dass du die CC-Bedingungen erfüllen kannst. Mit dieser Anpassung wollen wir letztlich genug Flexibilität herstellen, dass das mit diesem Profil möglich wird (entweder als Erweiterung oder perspektivisch sogar als Teil dieser Spezifikation).

Konkret könntest du in den Metadaten einen Array mit Informationen zu allen anchgenutzten Ressourcen pflegen. Beispiel (aus https://github.com/dini-ag-kim/licenseinformation-examples/tree/master/global-oer-logo reinkopiert):

```json
{
   "@context":[
      "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
      {
         "@language":"de"
      }
   ],
   "id":"https://example.org/beispielressource",
   "isBasedOn":[
      {
         "id":"https://commons.wikimedia.org/entity/M18460156",
         "name":"Global OER Logo",
         "license":{
            "id":"https://creativecommons.org/licenses/by/3.0/",
            "name":"Creative Commons Attribution 3.0 Unported"
         },
         "creator":{
            "id":"https://commons.wikimedia.org/wiki/User:Jonathasmello",
            "name":"Jonathas Mello"
         },
         "provider":{
            "id":"http://www.wikidata.org/entity/Q565",
            "name":"Wikimedia Commons"
         }
      }
   ]
}
```
> In der Praxis wüsste ich nicht, welche URI ich bei der Weiternutzung von OER für `wasAttributedTo` benutzen würde. Für mich selbst nutze ich aktuell `https://lechten.gitlab.io/#me`. Empfehlungen wären sinnvoll.

Idealerweise hätte natürlich jede Person eine Cool URI, die sie identifiziert und weitere strukturierte Daten vorhält, mit ORCID gibt es sowas ja auch immer häufiger. Bei unserem Ansatz hier ist das aber nicht entscheiden, weil du im `creator´-Objekt einfach auf die URI verzichten kannst, wenn es keine gibt und dann eben nur den Namensstring hast.

> Wenn `isBasedOn` eine [Cool URI](https://www.w3.org/TR/cooluris/) wäre (was ich bei `wasAttributedTo` unterstelle), würde ich bei deren Aufruf die Informationen zu Name, Lizenz usw. erwarten. Gibt es für meine OER aktuell nicht.

Klar, dass wäre so die Idealumsetzung von Linked Data und du bist ja auf einem guten Weg dahin. Letztenendes wir mensch aber noch für längere Zeit zumindest in einigen Fällen die Metadaten zu genutzen Ressourcen für eine akkurate Attribution selbst erfassen müssen. Dieses Ticket möchte die Möglichkeit eröffnen, diese Daten auf Basis des LRMI-Profils angeben zu können.

**Comment by lechten** [comment]
Hallo Adrian, vielen Dank für die ausführliche Antwort. Im Treffen habe ich nur kurz "Provenance" aufgeworfen, diskutiert haben wir das nicht.
Ja, aktuell versuche ich, Metadaten so anzugeben, dass die in Lizenzen geforderten Informationen vorliegen (weitere LRMI-Daten stehen auf meiner Todo-Liste). Ich stimme zu, mit obigem Mechanismus wird das möglich.

Was mir bei JSON-LD generell nicht gefällt, ist, dass ich die Daten zwei- bis dreimal angeben würde: Zuerst für Menschen lesbar. Diesen Teil könnte ich dann direkt semantisch mit RDFa annotieren. Schließlich noch das JSON. Mal sehen, ob/wann ich dazu komme, das zu generieren...

**Comment by acka47** [comment]
> Was mir bei JSON-LD generell nicht gefällt, ist, dass ich die Daten zwei- bis dreimal angeben würde: Zuerst für Menschen lesbar. Diesen Teil könnte ich dann direkt semantisch mit RDFa annotieren. Schließlich noch das JSON. Mal sehen, ob/wann ich dazu komme, das zu generieren...

Wenn du RDFa hast und das für dich am leichtesten einzubetten ist, dann reicht das völlig aus. Du musst und solltest dann nicht zusätzlich JSON-LD einbetten. Für OERSI können wir uns auch ohne Probleme RDFa ziehen und verarbeiten. Es ist aber ein guter Hinweis und wir sollten dahzu was in die Spec schreiben.

**Comment by acka47** [comment]
@lechten wrote in https://github.com/dini-ag-kim/lrmi-profile/pull/39#issuecomment-742390237:

> Manche OER-Lizenzen erfordern Angaben zu Änderungen, was wieder in Richtung Provenance geht, hier aber noch nicht abgebildet ist.

Da habe ich bereits mit @TobiasNx drüber diskutiert. Um solche Informationen zu ergänzen, müssten wir einen Node für die Aktion der Nachnutzung selbst ergänzen ("another level of indirection"), denn wir können diese Informationen nicht an das `isBasedOn`-Objekt anhängen, weil das ja die nachgenutzte Ressource selbst beschreibt.

Von daher würde ich im Kontext dieses Profils gerne davon absehen, das zu ergänzen, um es nicht zu komplex zu machen.

**Comment by lechten** [comment]
Richtig, das könnte ein `wasGeneratedBy` mit einer Aktivität bei PROV sein, zusätzlich zu `isBasedOn`.
