### ISSUE TITLE
`license`-Feld Vokabular erweitern

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/lrmi-profile#37]
Da das lrmi-profil nicht mehr nur zur Erfassung von OER dienen soll, brauchen wir eine Öffnung des Vokabulars für das `license`-Feld, damit auch andere Lizenzen und der Verweis auf vorbehaltene Rechte mit erfasst werden können.

**Comment by oellers** [comment]
Für Neuveröffentlichungen wäre eine CC-Lizenzierung denkbar und auch für Autoren sind diese sicherlich am einfachsten nutzbar. Besonders größere Ressourcen (z.B. Kurse oder Software) umfassen jedoch häufig andere oder mehrere Lizenztypen. Auch ist es manchmal nicht möglich eine Relizenzierung vorzunehmen.

Ein möglicher Anhaltspunkt vom Institut für Rechtsfragen der Freien und Open Source Software:
https://ifross.github.io/ifrOSS/Lizenzcenter sowie die [Übersicht kompatibler Lizenzen von GNU](https://www.gnu.org/licenses/license-list.html.en) und die [Vergleichsübersicht (Wikipedia)](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences) oder die [GitHub Licenses](https://choosealicense.com/licenses/)

Vorschlag für mögliche Erweiterungen:
- GNU GPL
- GNU LGPL
- GNU AGPL
- BSD 
- MIT 
- Apache

**Comment by acka47** [comment]
> Besonders größere Ressourcen (z.B. Kurse oder Software) umfassen jedoch häufig andere oder mehrere Lizenztypen.

@oellers, für #87 (dazugehöriger PR ist #88) haben wir entschieden, nur eine Lizenz pro Ressource zu erlauben. Hältst du diese Entscheidung für falsch, weil es doppelt lizenzierte Ressourcen gibt oder komplexe Ressourcen, die aus unterschiedlich lizenzierten Teilen bestehen? (Ich ergänze mal einen Agendapunkt für das Treffen am Dienstag.)

 we decided to only allow one license per resource by not allowing an array. Do you think we should change this to an array? We

**Comment by acka47** [comment]
Im OERSI-Kontext wurden wir auf die [SPDX License List](https://spdx.org/licenses/) hingewiesen (siehe [diesen Kommentar](https://gitlab.com/oersi/oersi-backend/-/issues/31#note_618828523)), die es auch als strukturierte Daten gibt, siehe https://github.com/spdx/license-list-data.

@mirjan-hoffmann, @TobiasNx und ich hatten uns auf die Idee geeinigt, die Angabe der Lizenz dahingehend zu erweitern, dass wir sämtliche in SPDX gelisteten Lizenz-URLs erlauben. Das heißt, wir würden uns aus den Dateien jeweils die `spdx:url`-Angabe holen – eventuell etwas anpassen, weil bei CC-Lizenzen z.B. die URL mit `legalcode` am Ende genutzt wird – und als `enum` im Schema ergänzen. So würden wir nicht jede beliebige URI erlauben aber eine umfangreiche Liste von URIs von Lizenzen.

**Comment by acka47** [comment]
> @mirjan-hoffmann, @TobiasNx und ich hatten uns auf die Idee geeinigt, die Angabe der Lizenz dahingehend zu erweitern, dass wir sämtliche in SPDX gelisteten Lizenz-URLs erlauben. Das heißt, wir würden uns aus den Dateien jeweils die `spdx:url`-Angabe holen – eventuell etwas anpassen, weil bei CC-Lizenzen z.B. die URL mit `legalcode` am Ende genutzt wird – und als `enum` im Schema ergänzen. So würden wir nicht jede beliebige URI erlauben aber eine umfangreiche Liste von URIs von Lizenzen.

Ich habe mal eine entsprechende Liste erstellt, siehe https://github.com/dini-ag-kim/license/blob/main/spx-license-urls.txt. Da sind alle unikalen SPX-Lizenz-URLs (`spdx:url`) drin. Schaue ich mir die Liste so an, bin ich aber nicht mehr sicher, ob das der richtige Ansatz ist. Offensichtlich ist das jeweils die URL auf den Lizenztext aber nicht unbedingt die URL, die mensch in RDF mit `sdo:license` verwenden würde. (Das `legalcode`-Suffix bei den CC-URLs hat das ja schon angedeutet.)

Was meint ihr?

**Comment by TobiasNx** [comment]
Ich hab gerade mal geschaut, du hast recht:
z.B. https://www.gnu.org/licenses/license-list.html#ACDL

wäre keine solche URI.

Vielleicht sollten wir dann den etwas pragmatischeren Ansatz von @oellers und erstmal die kleine Erweiterung ermöglichen.

![grafik](https://user-images.githubusercontent.com/61879957/128481711-f7f11815-02f5-45f5-bf3d-313b0cff53d1.png)

https://openedreader.org/front-matter/intro/

Das entspricht ja Vorgabe von Manuel.

**Comment by TobiasNx** [comment]
```
https://creativecommons.org/licenses/by/1.0/
https://creativecommons.org/licenses/by/2.0/
https://creativecommons.org/licenses/by/2.5/
https://creativecommons.org/licenses/by/2.5/au/
https://creativecommons.org/licenses/by/3.0/
https://creativecommons.org/licenses/by/3.0/at/
https://creativecommons.org/licenses/by/3.0/us/
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by-nc/1.0/
https://creativecommons.org/licenses/by-nc/2.0/
https://creativecommons.org/licenses/by-nc/2.5/
https://creativecommons.org/licenses/by-nc/3.0/
https://creativecommons.org/licenses/by-nc/4.0/
https://creativecommons.org/licenses/by-nc-nd/2.0/
https://creativecommons.org/licenses/by-nc-nd/2.5/
https://creativecommons.org/licenses/by-nc-nd/3.0/
https://creativecommons.org/licenses/by-nc-nd/3.0/igo/
https://creativecommons.org/licenses/by-nc-nd/4.0/
https://creativecommons.org/licenses/by-nc-sa/1.0/
https://creativecommons.org/licenses/by-nc-sa/2.0/
https://creativecommons.org/licenses/by-nc-sa/2.5/
https://creativecommons.org/licenses/by-nc-sa/3.0/
https://creativecommons.org/licenses/by-nc-sa/4.0/
https://creativecommons.org/licenses/by-nd/1.0/
https://creativecommons.org/licenses/by-nd/2.0/
https://creativecommons.org/licenses/by-nd/2.5/
https://creativecommons.org/licenses/by-nd/3.0/
https://creativecommons.org/licenses/by-nd/4.0/
https://creativecommons.org/licenses/by-nd-nc/1.0/
https://creativecommons.org/licenses/by-sa/1.0/
https://creativecommons.org/licenses/by-sa/2.0/
https://creativecommons.org/licenses/by-sa/2.0/uk/
https://creativecommons.org/licenses/by-sa/2.1/jp/
https://creativecommons.org/licenses/by-sa/2.5/
https://creativecommons.org/licenses/by-sa/3.0/
https://creativecommons.org/licenses/by-sa/3.0/at/
https://creativecommons.org/licenses/by-sa/4.0/
https://creativecommons.org/licenses/publicdomain/
https://creativecommons.org/publicdomain/zero/1.0/
http://www.gnu.org/licenses/gpl-3.0
http://www.gnu.org/licenses/gpl-2.0
http://www.gnu.org/licenses/gpl-1.0
http://www.gnu.org/licenses/lgpl-3.0
http://www.gnu.org/licenses/lgpl-2.1
http://www.gnu.org/licenses/agpl-3.0
http://www.gnu.org/licenses/fdl-1.3
http://www.gnu.org/licenses/fdl-1.2
http://www.gnu.org/licenses/fdl-1.1
http://www.apache.org/licenses/LICENSE-2.0
http://www.apache.org/licenses/LICENSE-1.1
http://www.apache.org/licenses/LICENSE-1.0
```

Bei MIT und BSD bin ich mir im unklaren, was die URI sein sollte.

**Comment by mirjan-hoffmann** [comment]
Im OERSI wird derzeit für MIT folgende URL verwendet: https://opensource.org/licenses/MIT
-> denke, das macht Sinn.

Für BSD könnte man auch die URLs von `https://opensource.org/licenses/` verwenden...

**Comment by TobiasNx** [comment]
https://creativecommons.org/licenses/by/1.0/
https://creativecommons.org/licenses/by/2.0/
https://creativecommons.org/licenses/by/2.5/
https://creativecommons.org/licenses/by/2.5/au/
https://creativecommons.org/licenses/by/3.0/
https://creativecommons.org/licenses/by/3.0/at/
https://creativecommons.org/licenses/by/3.0/us/
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by-nc/1.0/
https://creativecommons.org/licenses/by-nc/2.0/
https://creativecommons.org/licenses/by-nc/2.5/
https://creativecommons.org/licenses/by-nc/3.0/
https://creativecommons.org/licenses/by-nc/4.0/
https://creativecommons.org/licenses/by-nc-nd/2.0/
https://creativecommons.org/licenses/by-nc-nd/2.5/
https://creativecommons.org/licenses/by-nc-nd/3.0/
https://creativecommons.org/licenses/by-nc-nd/3.0/igo/
https://creativecommons.org/licenses/by-nc-nd/4.0/
https://creativecommons.org/licenses/by-nc-sa/1.0/
https://creativecommons.org/licenses/by-nc-sa/2.0/
https://creativecommons.org/licenses/by-nc-sa/2.5/
https://creativecommons.org/licenses/by-nc-sa/3.0/
https://creativecommons.org/licenses/by-nc-sa/4.0/
https://creativecommons.org/licenses/by-nd/1.0/
https://creativecommons.org/licenses/by-nd/2.0/
https://creativecommons.org/licenses/by-nd/2.5/
https://creativecommons.org/licenses/by-nd/3.0/
https://creativecommons.org/licenses/by-nd/4.0/
https://creativecommons.org/licenses/by-nd-nc/1.0/
https://creativecommons.org/licenses/by-sa/1.0/
https://creativecommons.org/licenses/by-sa/2.0/
https://creativecommons.org/licenses/by-sa/2.0/uk/
https://creativecommons.org/licenses/by-sa/2.1/jp/
https://creativecommons.org/licenses/by-sa/2.5/
https://creativecommons.org/licenses/by-sa/3.0/
https://creativecommons.org/licenses/by-sa/3.0/at/
https://creativecommons.org/licenses/by-sa/4.0/
https://creativecommons.org/licenses/publicdomain/
https://creativecommons.org/publicdomain/zero/1.0/
http://www.gnu.org/licenses/gpl-3.0
http://www.gnu.org/licenses/gpl-2.0
http://www.gnu.org/licenses/gpl-1.0
http://www.gnu.org/licenses/lgpl-3.0
http://www.gnu.org/licenses/lgpl-2.1
http://www.gnu.org/licenses/agpl-3.0
http://www.gnu.org/licenses/fdl-1.3
http://www.gnu.org/licenses/fdl-1.2
http://www.gnu.org/licenses/fdl-1.1
http://www.apache.org/licenses/LICENSE-2.0
http://www.apache.org/licenses/LICENSE-1.1
http://www.apache.org/licenses/LICENSE-1.0
https://opensource.org/licenses/MIT
https://opensource.org/licenses/BSD-3-Clause
https://opensource.org/licenses/BSD-2-Clause

**Comment by mirjan-hoffmann** [comment]
Ich denke, dass die Änderungen aus diesem Ticket hier problematisch sein können und mache es daher nochmal auf.

Vor der Änderung wurden jegliche CC Lizenzen zugelassen. Nun wird aber eine feste Liste definiert, die auf den ersten Blick nicht alle CC-Lizenzen zulässt. So fehlen zB die meisten der länderspezifischen Lizenzen wie https://creativecommons.org/licenses/by/3.0/br/, https://creativecommons.org/licenses/by/3.0/de/, ... . Außerdem sind die verschiedenen Schreibweisen der URL nicht berücksichtigt und zuvor gültige URLs wie `https://creativecommons.org/licenses/by/4.0` (ohne `/` am Ende) oder `https://creativecommons.org/licenses/by/4.0/deed.en` wären nun nicht mehr zulässig.

Sollte ich hier etwas übersehen, dann reicht mir eine kurze Erklärung und Ticket wieder zu.

**Comment by TobiasNx** [comment]
Ich hab es einmal umgestellt und ein oneOf anstatt ein enum genommen, das erlaubt uns die Offenheit.
Dennoch müsste einmal darüber nachgedacht werden, ob die Creative Commons Lizenzen in allen Schreibweisen zulässig sein sollten.

Wenn z.B. https://creativecommons.org/licences/by/4.0/ mit zwei "c" in licences genutzt wird, dann gibt es einen Redirekt auf https://creativecommons.org/licenses/by/4.0/.

Zusätzlich gibt es länderspezifische Anhängsel eigentlich nur bis CC-Lzenzen der Generation 3. Danach funktioniert CC eigentlich als globale Lizenz:
https://wiki.creativecommons.org/wiki/License_Properties#Inspecting_the_URL

Die Anhängsel "deed.en" oder "deed.de" sind Übersetzungsverweise.

**Comment by mirjan-hoffmann** [comment]
Ja, ich stimme zu, dass einmal darüber nachgedacht werden sollte, ob nur eine schreibweise oder mehrere für ein und dieselbe Lizenz zugelassen werden sollte. Wenn man mehr zulässt, dann orientiert sich das eher an der Praxis, da existierende Materialien derzeit viele unterschiedliche Schreibweisen verwenden. Möchte man es vereinheitlichen, dann wäre für solche Materialien immer auch ein Mapping notwendig - welche Vorteile hätte man denn durch eine Vereinheitlichung?

Länderspezifische Lizenzen gibt es nur bis zur Version 3, das stimmt. Diese werden aber auch genutzt (auch wenn oftmals empfohlen wird Version 4 zu nutzen) - daher sollten diese Lizenzen unbedingt unterstützt werden.

**Comment by acka47** [comment]
Ich finde @TobiasNx's Lösung in  https://github.com/dini-ag-kim/lrmi-profile/commit/cee95f1832fc8e1b9d3ea8ff9ba7a0afb036dca1 super und denke, wir können das erstmal so mergen. Die Vereinheitlichung der URLs für ORCA können wir ja im ETL umsetzen.
