### ISSUE TITLE
learningResourceType - Array?

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/lrmi-profile#38]
Aktuell ist `learningResourceType` ein Objekt, welches sowohl die id, als auch den Namen umfasst. Damit kann man aber mögliche Mischformen nicht berücksichtigen.

Mein Beispiel wäre, dass Videos auch Kurse oder Präsentationen sein können. @acka47 meinte dazu, dass es wenig Überschneidungen gebe. Video sei, wenn ein Bestandteil eines Kurses und Präsentation beziehe sich auf die Slides.

@acka47  und ich waren uns einig. dass wir es aber einmal diskutieren sollten.

**Comment by acka47** [comment]
Im letzten Gruppentreffen haben wir beschlossen ([siehe Notizen](https://pad.gwdg.de/s/S1TZDXU2P#learningResourceType-als-Array---Ja)), hier einen Array zu verlangen. Das ist auch analog zur LOM-Spezifikation, siehe https://dini-ag-kim.github.io/hs-oer-lom-profil/latest/#das-element-learningresourcetype.

**Comment by TobiasNx** [comment]
Hi @acka47 , ich erhalte bei akj folgende Fehlermeldung: In schema.json kommt das Keyword auch nicht vor, wohl aber in allen Unterschemas.

bash test.sh
Testing version: draft
schema draft/schemas/schema.json is invalid
error: strict mode: unknown keyword: "_display"

Kannst du mir da helfen?

**Comment by acka47** [comment]
Das ist eines der Probleme mit neueren ajv-Versionen. Du installierst am besten ajv-cli version 3.0:

`$ npm install -g ajv-cli@3.0.0`

Siehe auch die [`.travis.yml`](https://github.com/dini-ag-kim/lrmi-profile/blob/d02536adfc28e74e89cd80c70487ed4d353fc831/.travis.yml#L4).

**Comment by TobiasNx** [comment]
Danke. Validiert jetzt, super!
