### ISSUE TITLE
Probleme mit data-include in Markdown-Datei

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/lrmi-profile#53]
In der `profile.md` befindet sich folgendes:

```html
<section id="type-example">
<h2>Beispiel</h2>
<pre class="example" data-include="draft/examples/valid/learningResourceType.json" data-include-format="text"></pre>
</section>

```

Leider wird das Beispiel aber nicht angezeigt, siehe https://dini-ag-kim.github.io/lrmi-profile/draft/#type-example oder beim okal gebauten http://localhost:8000/draft/#type-example.

Ich weiß nicht, ob es an der Art der Referenz liegt (auf eine Datei in einem Ordner auf einer anderen Ebene. Dagegen spricht, dass die Einbettung auch mit einem absoluten Link nicht funktioniert, weder mit `/draft/examples/valid/learningResourceType.json` noch mit `/examples/valid/learningResourceType.json`.

Deshalb glaube ich eher, dass das Problem daher rührt, dass die Referenz aus einem markdwon-Dokument kommt.

**Comment by acka47** [comment]
@sebastian-meyer, fällt dir dazu vielleicht spontan was ein?

**Comment by fsteeg** [comment]
> ` data-include="draft/examples/valid/learningResourceType.json"`

Ich glaube der Pfad muss relativ zur index.html sein, also hier `examples/valid/learningResourceType.json` (oder in dem Fall relativ zur profile.md? `../examples/valid/learningResourceType.json`).

**Comment by sebastian-meyer** [comment]
ReSpec ist etwas empfindlich, wenn es um `data-include` innerhalb von `data-include` geht. Die Datei `profile.md` wird ja selbst schon per `data-include` eingebunden, deshalb funktionieren `data-include` darin unter Umständen nicht mehr. Das ist nach meiner Erfahrung ein Problem der asynchronen Funktionsweise von `data-include`: ReSpec initiiert die Einbettung von `profile.md`, wartet mit der weiteren Prozessierung der `data-include`-Anweisungen aber nicht darauf.

Das Problem tritt aber nur bei Markdown-Dateien auf, da inkludierte HTML-Dateien automatisch ihrerseits einen ReSpec-Durchlauf triggern. Es ist verwirrend und für mich auch nicht nachvollziehbar, warum ReSpec Markdown anders behandelt als HTML.

**Comment by acka47** [comment]
Danke, @sebastian-meyer, für die Erklärung. Ich nehme das `data-include` dann mal aus der Markdown-Datei raus. Bin ohnehin nicht sicher, ob wir bei den einzelnen Feldern Beispiele einbeeten wollen. Wenn wir das zuküntig benötigen sollten, müssen wir die Inhalte halt als HTML pflegen.
