### ISSUE TITLE
Entferne custom keys im JSON Schema

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/lrmi-profile#61]
Bei der Validierung in OERSI werden folgende Warnungen zurückgemeldet:

```
WARN  [main] [JsonMetaSchema] Unknown keyword additionalItems - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
WARN  [main] [JsonMetaSchema] Unknown keyword _display - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
WARN  [main] [JsonMetaSchema] Unknown keyword suggested - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
WARN  [main] [JsonMetaSchema] Unknown keyword _widget - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
```

Man kann dabei nicht eindeutig erklären, welches Schema diese hervorruft. Aber müssen wir hier etwas tun?

**Comment by acka47** [comment]
Das sind teilweise custom keys für den SkoHub Editor. Ich denke, wir sollten diese rausnehmen, weil das im Kontext der Spezifikation nur zu Verwirrung führt.

**Comment by acka47** [comment]
Wir sollten die Custom Keys kurz vor der Publikation entfernen und im gleichen Zuge https://github.com/skohub-io/skohub-editor/blob/422d494447a8e1816063e25783c6c4643eb0ab7b/src/components/SkohubEditor.js#L16 anpassen.

**Comment by acka47** [comment]
Ich habe den derzeitigen Stand des Profils nach https://github.com/skohub-io/metadata-profiles/tree/main/lrmi-profile kopiert, dort die Schemas mit GitHub pages veröffentlicht und einen PR zur Änderung des Default Schemas im SkoHub Editor geöffnet: https://github.com/skohub-io/skohub-editor/pull/75

Sobald der PR gemergt und deployt ist, können wir die custom keys in diesem Repo entfernen.
