### ISSUE TITLE
learningResourceType.json - Schemaergänzung + Validierungspattern aktualisieren

### ISSUE THREAD

**Issue by oellers** [dini-ag-kim/lrmi-profile#74]
Die [HTML-Spezifikation](https://dini-ag-kim.github.io/lrmi-profile/draft/#learningresourcetype) benennet als valide Werte für learningResourceType zwei Vokabulare.

[learningResourceType.json:](https://github.com/dini-ag-kim/lrmi-profile/blob/master/draft/schemas/learningResourceType.json)
- [x] Zweites Schema ergänzen
- [x] Validierungspattern aktualisieren

- [x] className: hidden entfernen? / learningResourceType im [SkoHub-Editor](https://skohub.io/editor/) anzeigen (in [HTML-Spezifikation](https://dini-ag-kim.github.io/lrmi-profile/draft/#learningresourcetype) als Pflichtfeld deklariert, jedoch dort nicht vorhanden?)

**Comment by acka47** [comment]
Danke für die Rückmeldungen, Manuel.

> Zweites Schema ergänzen
> Validierungspattern aktualisieren

Werde ich tun.

> className: hidden entfernen? / learningResourceType im SkoHub-Editor anzeigen (in HTML-Spezifikation als Pflichtfeld deklariert, jedoch dort nicht vorhanden?)

Wir werden die Editor-spezifischen Angaben ohnehin rausnehmen und dann ein separates Schema für den Editor anlegen, siehe #61.
