### ISSUE TITLE
Ändern der empfohlenen Fächerliste in `about` für Schulbereich

### ISSUE THREAD

**Issue by sroertgen** [dini-ag-kim/lrmi-profile#80]
Im Rahmen der DINI-AG-KIM ist eine Werteliste erarbeitet worden, die für die Bezeichnung des Schulfaches in diesem Profil der DINI-AG-KIM verwendet werden sollte: https://github.com/dini-ag-kim/schulfaecher .

Diese sollte mit der projektspezifische Liste des OpenEduHub, die momentan als Referenz genannt wird, getauscht werden.

**Comment by acka47** [comment]
Danke, da habe ich nicht aufgepasst als ich das die Tage implementiert habe.
