### ISSUE TITLE
Ermögliche Angabe von Download-Links der Ressource

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/lrmi-profile#82]
Für die Umsetzung bietet sich [`sdo:associatedMedia`](https://schema.org/associatedMedia) an:

> A media object that encodes this CreativeWork. This property is a synonym for encoding.

Das Ergebnis könnte dann etwa so aussehen:

```json
{
"@context": "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
  "id":"https://example.org/oer",
  "name":"Beispiel-OER",
  "description":"Beispiel-OER mit Download-Formaten HTML, Markdown und PDF",
  "associatedMedia":[
    {
      "type":"MediaObject",
      "contentUrl":"https://example.org/oer.md",
      "encodingFormat":"text/markdown"
    },
    {
      "type":"MediaObject",
      "contentUrl":"https://example.org/oer.html",
      "encodingFormat":"text/html"
    },
    {
      "type":"MediaObject",
      "contentUrl":"https://example.org/oer.pdf",
      "encodingFormat":"application/pdf"
    }
  ]
}
```

**Comment by acka47** [comment]
Ich glaube, wir sollten hier besser [`sdo:encoding`'](https://schema.org/encoding) verwenden, das ein Synonym für `associatedMedia` ist. Wir könnten in diesem Zuge auch eine Use Case umsetzen, der für OERSI und ORCA nützlich ist: Angabe der URL zum Einbetten eines Videos. Das könnte etwa so aussehen (am Beispiel [dieser OERSI-Ressource](https://oersi.de/resources/aHR0cHM6Ly9hdi50aWIuZXUvbWVkaWEvMzI2NDE=?format=json)):

```json
{
  "@context":[
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {
      "@language":"de"
    }
  ],
  "inLanguage":[
    "en"
  ],
  "id":"https://av.tib.eu/media/32641",
  "learningResourceType":[
    {
      "id":"https://w3id.org/kim/hcrt/video",
      "prefLabel":{
        "de":"Video",
        "en":"Video"
      }
    }
  ],
  "image":"https://av.tib.eu/thumbnail/32641",
  "encoding":[
    {
      "encodingFormat":"video/mp4",
      "contentSize":"567MB",
      "url":"https://tib.flowcenter.de/mfc/medialink/3/dea844a48268f9c1d10e340613eb0d0c87fcdc8e04b9980efa06743a026e99a979/_FOSDEM_2014__The_road_ahead_for_network_freedom_4vNMAOJDhhw_v1500a128.mp4",
      "embedUrl":"https://av.tib.eu/media/32641"
    },
    {
      "encodingFormat":"video/mp4",
      "contentSize":"285MB",
      "url":"https://tib.flowcenter.de/mfc/medialink/3/dececd3fadf9ab5d198c6c2fb886fadacfe208efc67b76c5f2503dab055bace61b/_FOSDEM_2014__The_road_ahead_for_network_freedom_4vNMAOJDhhw.mp4"
    }
  ]
}
```

**Comment by mirjan-hoffmann** [comment]
Hallo @acka47, ich habe dies gerade mal mit @axel-klinger diskutiert. Grundsätzlich finden wir die Idee gut und befürworten die Umsetzung. Was uns noch bei den einzelnen `MediaObject`-Einträgen fehlt, ist ein Feld für den Titel oä. Ggf. auch eine Beschreibung. Ansonsten wird es schwierig dem User eine "schöne" Download-Link-Liste anzubieten und der User weiß dann nicht was sich hinter welchem Link verbirgt.

**Comment by acka47** [comment]
> Was uns noch bei den einzelnen MediaObject-Einträgen fehlt, ist ein Feld für den Titel oä. Ggf. auch eine Beschreibung.

Danke für den Vorschlag, den ich voll unterstütze. Die konkrete Umsetzung hängt davon ab, was in diesem Textstring stehen soll. Ich gehe davon aus, dass es eher eine Beschreibung im Kontext der ganzen Ressource sein soll als ein kompletter Namen für das Objekt. Konkret, eher etwas in die Richtung "mp4, gute Qualität" und nicht ein umfassender Titel wie z.B. "MP4-Video 'The road ahead for network freedom', Christopher Webber in guter Qualität".

Wenn dem so ist, tendiere ich dazu, `sdo:description` und nicht `sdo:name` zu benutzen. Das Ergebnis würde dann so aussehen:

```json
{
  "@context":[
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {
      "@language":"de"
    }
  ],
  "inLanguage":[
    "en"
  ],
  "id":"https://av.tib.eu/media/32641",
  "learningResourceType":[
    {
      "id":"https://w3id.org/kim/hcrt/video",
      "prefLabel":{
        "de":"Video",
        "en":"Video"
      }
    }
  ],
  "image":"https://av.tib.eu/thumbnail/32641",
  "encoding":[
    {
      "type": "MediaObject",
      "encodingFormat":"video/mp4",
      "description": "mp4, gute Qualität",
      "contentSize":"567MB",
      "contentUrl":"https://tib.flowcenter.de/mfc/medialink/3/dea844a48268f9c1d10e340613eb0d0c87fcdc8e04b9980efa06743a026e99a979/_FOSDEM_2014__The_road_ahead_for_network_freedom_4vNMAOJDhhw_v1500a128.mp4"
    },
    {
      "type": "MediaObject",
      "encodingFormat":"video/mp4",
      "contentSize":"285MB",
      "description": "mp4, normale Qualität",
      "contentUrl":"https://tib.flowcenter.de/mfc/medialink/3/dececd3fadf9ab5d198c6c2fb886fadacfe208efc67b76c5f2503dab055bace61b/_FOSDEM_2014__The_road_ahead_for_network_freedom_4vNMAOJDhhw.mp4",
      "embedUrl":"https://av.tib.eu/media/32641"
    }
  ]
}
```

**Comment by mirjan-hoffmann** [comment]
Das ist schwierig zu beantworten, da ich keine Praxisbeispiele finden kann wo diese Informationen in den Metadaten bereitgestellt werden. In den verfügbaren Metadaten des AV-Portals gibt es zB gar keine Angabe über Download-Links - das embedding kann man sich auch nur selbst konstruieren. Auch in den anderen Quellen, die wir im OERSI nutzen (wie zB HHU Mediathek), kann ich solche Download-Informationen nicht in den Metadaten finden. Im OERSI würde es daher vermutlich eh erstmal nur auf (konstruierte) embed-URLs hinauslaufen...

Prinzipiell würde ich es aber vermeiden eine technische Beschreibung der Resource als Freitext aufzunehmen und lieber "standardisierte" Felder verwenden. In Deinem Beispiel könnte man die gleiche Information auch über die Felder `encodingFormat` und `bitrate` angeben und hätte damit auch den Vorteil, das man die Beschreibung in verschiedenen Sprachen angeben könnte. Vielleicht wäre sowas ja auch schon ausreichend um Download-Links beschriften zu können?

Wenn ich als weiteres Beispiel daran denke, dass mehrere Textdokumente oder auch mehrere Bilder aufgeführt werden, dann macht die Verwendung eines "Titel"-Feldes doch schon wieder mehr Sinn. Evtl lässt man den Punkt auch erstmal noch offen und ergänzt dies später wenn Praxisbeispiele vorliegen? Was meinst Du? Evtl kannst Du auch bzgl des ORCA use case nochmal nachhaken?

**Comment by acka47** [comment]
Es wäre auch sinnvoll, die Prüfsumme der Datei mitgeben zu können. schema.org scheint dafür aber noch keine Property zu haben und ich konnte auch kein Ticket dazu finden ([Proposal: Standardize the time-stamping of content](https://github.com/schemaorg/schemaorg/issues/2756) beinhaltet aber einen Vorschlag für die Angabe einer Prüfsumme/eines Hashs).

**Comment by acka47** [comment]
> In Deinem Beispiel könnte man die gleiche Information auch über die Felder `encodingFormat` und `bitrate` angeben und hätte damit auch den Vorteil, das man die Beschreibung in verschiedenen Sprachen angeben könnte. Vielleicht wäre sowas ja auch schon ausreichend um Download-Links beschriften zu können?

Ich gebe dir Recht, dass wir das weiterverfolgen sollten und `description` lieber rauslassen oder für andere Zwecke benutzen sollten. `encodingFormat` hatte ich schon drin. [´bitrate`](https://schema.org/bitrate) kann ich aber für das Beispiel nicht ergänzen, weil das AV Portal die Infos nicht liefert.

Ich kriegen langsam das Gefühl, dass wir vielleicht mal ein separates Treffen nur für videospezifische Metadaten machen sollten. Da könnte ich dann auch Leute aus dem ORCA.nrw-Kontext einladen, die Videos anbieten. Ich werde das kommenden Dienstag beim nächsten Treffen der OER-Metadatengruppe mal vorschlagen.

**Comment by mirjan-hoffmann** [comment]
> Es wäre auch sinnvoll, die Prüfsumme der Datei mitgeben zu können. schema.org scheint dafür aber noch keine Property zu haben und ich konnte auch kein Ticket dazu finden (Proposal: Standardize the time-stamping of content beinhaltet aber einen Vorschlag für die Angabe einer Prüfsumme/eines Hashs).

Was ist denn mit https://schema.org/MediaObject -> Property: `sha256`
Siehe auch https://schema.org/sha256

Das sollte es doch abdecken, oder?

**Comment by acka47** [comment]
> Was ist denn mit https://schema.org/MediaObject -> Property: `sha256`
> Siehe auch https://schema.org/sha256
>
> Das sollte es doch abdecken, oder?

Ja, super. Das hatte ich nciht gefunden.
