### ISSUE TITLE
Form der Erfassung von Personennamen spezifizieren

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/lrmi-profile#85]
Die Spezifikation legt nicht fest, wie Personennamen am besten angegeben werden sollten. Ich schlage vor, Personnamen vollständig in der üblichen Reihenfolge der jeweiligen Sprache (Deutsch: Vorname Nachname) zu erfassen. Siehe auch https://www.w3.org/International/questions/qa-personal-names.

**Comment by TobiasNx** [comment]
Aus meiner Sicht ist eine Klärung von Titel relevant. Also bspw. mit oder ohne Dr. oder Prof. Dr.
Ich wäre für ohne.

**Comment by acka47** [comment]
> Aus meiner Sicht ist eine Klärung von Titel relevant. Also bspw. mit oder ohne Dr. oder Prof. Dr.
Ich wäre für ohne.

+1 Ergänzt du einen Zusatz ("ohne Angabe von akademischen Titeln" o.ä.)?

**Comment by TobiasNx** [comment]
Sollte die Form der Namensnennung in den beiden Schema nicht auch ausgeführt werden?
