### ISSUE TITLE
`license`-Feld soll Objekt erwarten

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/lrmi-profile#87]
In ORCA wollen wir perspektivisch weitere Informationen zur Lizenz anpassen (z.B., dass sie zu einer Collection "CC-BY" gehört, in die wir alle CC-BY-Lizenzen unabhängig von Version und Land packen). Es gibt sicher auch andere Anwendungsfälle, wo so etwas nützlich ist, der einfachste wäre die Angabe eines Labels für die Lizenz in den Metadaten.

@TobiasNx , @mirjan-hoffmann und @acka47 haben deshalb beschlossen, dass die Objekt-Lösung die beste ist.

Es wird aber keinen Array geben, weil jede Ressource nur genau eine Lizenz haben soll.

**Comment by acka47** [comment]
@oellers schreibt in https://github.com/dini-ag-kim/lrmi-profile/issues/37#issuecomment-815864313:

> Besonders größere Ressourcen (z.B. Kurse oder Software) umfassen jedoch häufig andere oder mehrere Lizenztypen.

Wir hatten hier zunächst entschieden, nur eine Lizenz pro Ressource zu erlauben. Hältst du diese Entscheidung für falsch, @oellers, weil es doppelt lizenzierte Ressourcen gibt oder komplexe Ressourcen, die aus unterschiedlich lizenzierten Teilen bestehen? (Ich ergänze mal einen Agendapunkt für das Treffen am Dienstag.)

**Comment by oellers** [comment]
Am 13.07. hatten wir die Thematik nochmals erörtert (siehe [Notizen](https://pad.gwdg.de/2021-07-13-kim-oer)), Problem könnten zusammengesetzte Ressourcen, bspw. Präsentationen/Materialien, bestehend aus Inhalten/Bildern mit mehreren Lizenzen sein. Wenngleich theoretisch mit hasPart-Relationen gearbeitet werden könnte, dürfte das in der Praxis zunächst oft nicht der Fall sein.

Dennoch scheint zunächst eine einzelne Lizenz als Objekt hinreichend, da bei der Wiederverwendung der Metadaten der Zusatz "Soweit nicht anders gekennzeichnet" erfolgen könnte. 

Hier stellt sich die Frage, ob das Bestandteil des Objektes sein sollte oder ob das immer eine "implizite" Annahme ist.

**Comment by acka47** [comment]
> Hier stellt sich die Frage, ob das Bestandteil des Objektes sein sollte oder ob das immer eine "implizite" Annahme ist.

Denkst du an so etwas?

```json
{
  "@context":[
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
    {
      "@language":"de"
    }
  ],
  "id":"https://example.org/eine-oer",
  "type":"LearningResource",
  "license":{
    "id":"https://creativecommons.org/licenses/by/4.0/",
    "name":"Creative Commons Attribution 4.0 International",
    "description":"Lizenz CC-BY 4.0 soweit nicht anders gekennzeichnet"
  }
}
```

Das wäre leider nicht korrekt, weil die `description` ja keine Aussage über die Lizenz, sondern die OER macht. Das müsste dann anders modelliert werden, etwa so (nicht-schema.org-Properties mit `ex:` markiert):

```json
{
  "@context":[
    "https://w3id.org/kim/lrmi-profile/draft/context.jsonld"
    {
      "@language":"de"
    }
  ],
  "id":"https://example.org/eine-oer",
  "type":"LearningResource",
  "ex:licensing":{
    "description":"Lizenz CC-BY 4.0 soweit nicht anders gekennzeichnet",
    "ex:mainLicense":{
      "id":"https://creativecommons.org/licenses/by/4.0/",
      "name":"Creative Commons Attribution 4.0 International"
    }
  }
}
```

Das finde ich zu komplex und da gibt es – zumindest in schema.org – derzeit nicht die passenden Properties zu. Von daher würde ich das erstmal nicht machen.
